name: notification
on: workflow_dispatch
jobs:
  slack:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the reader
        uses: slackapi/slack-github-action@v2.1.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "Greetings!"
            channel: "deployments"
    
